### ISSUE TITLE
arm targets not compiling

### ISSUE THREAD

**Issue by mujehoxe** [panda-re/panda#1077]
```
/home/o/panda/disas/arm-a64.cc:20:1: note: 'extern "C"' linkage started here
20 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /home/o/panda/include/glib-compat.h:22,
                 from /home/o/panda/include/qemu/osdep.h:113,
                 from /home/o/panda/disas/arm-a64.cc:21:
/usr/include/c++/11.1.0/type_traits:2900:3: error: template with C linkage
 2900 |   template<typename _Fn, typename... _Args>
      |   ^~~~~~~~
/home/o/panda/disas/arm-a64.cc:20:1: note: 'extern "C"' linkage started here
   20 | extern "C" {
      | ^~~~~~~~~~
  CXX     disas/libvixl/vixl/compiler-intrinsics.o
make: *** [/home/o/panda/rules.mak:92: disas/arm-a64.o] Error 1
make: *** Waiting for unfinished jobs....
```

solved by only specifying non arm targets
../build.sh i386-softmmu

**Comment by rjzak** [comment]
I'm getting this issue too with gcc 8, 9, 10 on Pop_OS 21.04. But was able to compile on Ubuntu 20.04. I noticed that 21.04 has glib 2.64.2 while 21.04 has 2.68.1. This issue could be present in the next Ubuntu LTS release.

The issue is with having a `#include` inside of an `extern "C"`, where the included file uses templates. Extern C disables name mangling, which is needed by templates. https://stackoverflow.com/questions/4877705/why-cant-templates-be-within-extern-c-blocks

**Comment by AndrewFasano** [comment]
Thanks for tracking down the root cause and explaining it @rjzak, it's much appreciated! It sounds like the kind of thing we should fix, but it's mostly in the core qemu code not in our PANDA changes - hopefully upstream has a fix we can find and backport.
