### ISSUE TITLE
wireshark problem in arch linux

### ISSUE THREAD

**Issue by mujehoxe** [panda-re/panda#1078]
```
/home/o/panda/panda/plugins/network/network.cpp:22:10: fatal error: wireshark/config.h: No such file or directory
22 | #include <wireshark/config.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
  PLUGIN  x86_64-softmmu/panda/plugins/panda_coverage.so 
make[2]: *** [/home/o/panda/rules.mak:97: panda/plugins/network/network.o] Error 1
make[1]: *** [/home/o/panda/panda/Makefile.panda.target:44: plugin-network] Error 2
make[1]: *** Waiting for unfinished jobs....
  PLUGIN  x86_64-softmmu/panda/plugins/panda_osi.so 
  PLUGIN  x86_64-softmmu/panda/plugins/panda_mmio_trace.so 
make: *** [Makefile:358: subdir-x86_64-softmmu] Error 
```

solved by disabling the network plugin
(by commenting it out from panda/plugins/config.panda)

**Comment by moyix** [comment]
Tagging @nathanjackson to take a look if he has time. We should be able to modify the network plugin so that it doesn't rely on `config.h`, which is an artifact of the build process and not really meant to be exported (Debian/Ubuntu include it but most other distros do not).

Similar issue and patch in libvirt that we can probably crib from:

https://gitlab.com/libvirt/libvirt/-/issues/74

https://listman.redhat.com/archives/libvir-list/2020-September/msg00156.html

**Comment by nathanjackson** [comment]
I'm unlikely to get to this soon, please consider submitting a PR. I'd be happy to verify the plugin still works as expected after the patch.
