### ISSUE TITLE
Integrate out-of-tree plugin build

### ISSUE THREAD

**Issue by rjwhelan** [panda-re/panda#1088]
We have an out-of-tree plugin build process we'd like to integrate. This issue will track development.

**Comment by rjwhelan** [comment]
This repo lives [here](https://github.com/panda-re/panda-plugins), thanks to @Saccharide.

**Comment by Saccharide** [comment]
## Current plugin building process
The current plugins are built in tree, where they are being built under the corresponding architecture folder (i.e. `i386-softmmu/panda/plugins/`. This process definitely works, but I think it will be an improvement if the plugins can be developed and build at a separate location, independent of  PANDA core files as to building all the plugins and PANDA code at once in one location.

## Personal Plugin
* The current solution that addresses the above question would need to follow these 7 steps from [here](https://github.com/panda-re/panda/blob/dev/panda/docs/manual.md#personal-plugins)
1. Create a directory in which you will create personal plugins.  `/home/you/personal`
2. Create a subdirectory `personal/panda/plugins` there as well.
4. Say you have written a plugin you want to call `new_cool`.  Create a subdirectory `personal/panda/plugins/new_cool` and put the code for the new plugin there.
5. Create a file `panda/plugins/config.panda` with names of enabled plugins as you would normally.
6. You can use the the same makefile set-up as with regular plugins.
7. configure with `--extra-plugins-path=/home/you/personal`
8. Build as usual and you should compile `new_cool` plugin and its compiled code will be deposited in, e.g., `i386-softmmu/panda_plugins`

# Proposal of out-of-tree build
* We don't have to change anything to existing PANDA code at all, if people feel more comfortable with the traditional way of building and developing plugins, they can do that without a problem. Nothing is being changed  to `panda` repo.
 
## Benefit of an out-of-tree build 
* Makes PANDA more modular so that we can focus developing plugins separately from PANDA core development.
* Remove the overhead of reconfiguring and rebuilding PANDA if you change your personal plugin directory and adding the /pand/plugin/ directory prefix,
* Working prototype code [here](https://github.com/panda-re/panda-plugins) 

## Details of the out-of-tree build prototype
* It uses `cmake` as a wrapper to build PANDA plugins and PANDA itself.  The reason to include PANDA is because the plugins depends on PANDA hardware / plugin / architecture library code, and the use of a git submodule can be changed to symbolic link in the future if more people find that convenient. (As a git submodule is tied to a specific commit if PANDA is not updated) 
*  To build a plugin, we place the source code under the `plugins/` repo, and translate the corresponding `Makefile` to a `CMakeLists.txt` inside that directory.
*  Then we add it to the `plugins/CMakeLists.txt` with `add_subdirectory(PLUGIN_NAME)`
* After building the plugins repo, it will install the plugins to `/usr/local/bin`, which is one of the default path that PANDA searches plugins library at. This location can be modified by changing the `CMAKE_INSTALL_PREFIX` variable on the top level CMakeLists.txt

**Comment by saccharide** [comment]
## Current plugin building process
The current plugins are being built in-tree, where they are being built under the corresponding architecture folder (i.e. `i386-softmmu/panda/plugins/`. This process works, but I think it will be an improvement if the plugins can be developed and build independent of  PANDA core.

## Personal Plugin
* The current solution that addresses the above question would need to follow these 7 steps from [here](https://github.com/panda-re/panda/blob/dev/panda/docs/manual.md#personal-plugins)
1. Create a directory in which you will create personal plugins.  `/home/you/personal`
2. Create a subdirectory `personal/panda/plugins` there as well.
4. Say you have written a plugin you want to call `new_cool`.  Create a subdirectory `personal/panda/plugins/new_cool` and put the code for the new plugin there.
5. Create a file `panda/plugins/config.panda` with names of enabled plugins as you would normally.
6. You can use the the same makefile set-up as with regular plugins.
7. configure with `--extra-plugins-path=/home/you/personal`
8. Build as usual and you should compile `new_cool` plugin and its compiled code will be deposited in, e.g., `i386-softmmu/panda_plugins`

# Proposal of out-of-tree build
 
## Benefits of an out-of-tree build 
* Makes PANDA more modular so that we can focus developing plugins separately from PANDA core development.
* Remove the overhead of reconfiguring and rebuilding PANDA each time you changes your personal plugin directory and remove the `/panda/plugin/` directory prefix altogether, making it simpler to add new plugins.
* Working prototype code have been implemented [here](https://github.com/panda-re/panda-plugins)
* Can supports building different versions of panda plugins. (simply replace `plugins/dependency/panda-wrapper` to points to any version of PANDA, and make sure you have that version of the PANDA plugin source code inside `plugins/` repo and `plugin/CMakeLists.txt`. 
* We don't have to change anything to existing PANDA code at all, if people prefer the traditional way of building and developing plugins, they can still do that. Nothing new is being introduced to the `panda` repo.

## Details of the out-of-tree build prototype
* It uses `cmake` as a wrapper to build PANDA plugins and PANDA itself.  The reason to include PANDA is because the plugins depends on PANDA hardware / plugin / architecture library code, and the use of a git submodule can be changed to symbolic link in the future if more people find that convenient. (As a git submodule is tied to a specific commit if PANDA is not updated) 
*  To build a plugin, we place the source code under the `plugins/` repo, and translate the corresponding `Makefile` to a `CMakeLists.txt` inside that directory.
*  Then we add it to the `plugins/CMakeLists.txt` with `add_subdirectory(PLUGIN_NAME)`
* After building the plugins repo, it will automatically install plugins to `/usr/local/bin`, which is one of the default paths that PANDA searches. This location can be modified by changing the `CMAKE_INSTALL_PREFIX` variable on the top level CMakeLists.txt

## Limitation of the prototype 
* It currently only supports `i386` and `x86_64` architecture. However, adding other architecture are possible and require some additional work (i.e, creating another macro similar to `macro(add_i386_plugin)` inside `Macros.cmake`). 
* It builds PANDA as a dependency (which I think may be fine, but I think it is possible we can link the plugins directory to an existing PANDA binary directory without having to spend a lot of time rebuilding it)
* It currently only supports plugins written in C/C++. For example, rust plugins currently cannot be build with this prototype, but I think we can use `ExternalProject_Add` to make it build with cmake. <https://stackoverflow.com/questions/31162438/how-can-i-build-rust-code-with-a-c-qt-cmake-project>

**Comment by rjwhelan** [comment]
Closing this issue as it is complete and hasn't received any comments.  Open future issues at https://github.com/panda-re/panda-plugins.
