### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by s0i37** [panda-re/panda#1164]
Hello.
I am trying build panda as:
```
mkdir build; cd build
../build.sh i386-softmmu,x86_64-softmmu
```
And I've the following error:
```
    inlined from ‘vvfat_open’ at /opt/panda/block/vvfat.c:1181:9:
/opt/panda/block/vvfat.c:426:14: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  426 |     dest[2*i]=dest[2*i+1]=0;
      |     ~~~~~~~~~^~~~~~~~~~~~~~

```

Thank you!

**Comment by lacraig2** [comment]
Can you post some details of your environment? Specifically:
- Operating System
- gcc version
- Branch of PANDA you're building.

**Comment by Lancern** [comment]
I come across the same issue and I think I have figured out the cause.

Your `gcc` / `g++` version is too new, and they emit more warnings than older `gcc` / `g++` versions. `build.sh` actually detects this and tries to pass `-Wno-error` to `gcc` / `g++`:

https://github.com/panda-re/panda/blob/2d2358d714e8dd766fbc21a30d4a41a4c33fba04/build.sh#L67-L69

However, there is a bug above. At line 69, the value of `COMPILER_CONFIG` is overridden rather than appended, and thus `gcc` does not receive `-Wno-error` and cause the compile error.

The fix is rather simple. You can change `COMPILER_CONFIG=...` at line 69 to `COMPILER_CONFIG+=...` and add a whitespace before `--extra-cxxflags`, and the problem should be solved.
