### ISSUE TITLE
Compiler errors due to unrecognized gcc flags

### ISSUE THREAD

**Issue by Komasa** [panda-re/panda#131]
Trying to build PANDA with the current gcc on Arch Linux yields several errors concerning the used compiler flags:

> 
> $ cc --version
> cc (GCC) 6.3.1 20170109
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

> $ grep "cc: error:" config.log 
> cc: error: unrecognized command line option ‘-Wstring-plus-int’; did you mean ‘-Wstrict-aliasing’?
> cc: error: unrecognized command line option ‘-Winitializer-overrides’; did you mean ‘-Wno-suggest-override’?
> cc: error: unrecognized command line option ‘-nopie’; did you mean ‘-no-pie’?

**Comment by m000** [comment]
gcc 6.3 is pretty much bleeding edge (<1month since release).

I'd go with something more tested. E.g. I can't recall having any problems
with gcc 4.[89]. Or, if you have the time, you can lookup the equivalent
flags for gcc 6 and submit a patch for the build scripts.

M.

2017-01-17 18:32 GMT+01:00 Komasa <notifications@github.com>:

**Comment by moyix** [comment]
I think this turns out not to be a bug – those lines in config.log are related to testing what flags the compiler supports, so errors are expected.

**Comment by phulin** [comment]
I haven't tested myself, but I don't think this is a PANDA issue - I bet
you will get the same issue with upstream QEMU. Maybe it is because we
haven't pulled QEMU changes in a while.
