### ISSUE TITLE
Panda record/replay on nested vm fails with assertion error

### ISSUE THREAD

**Issue by Phasip** [panda-re/panda#1332]
Hello! I'm trying to run panda with my windows 10 image, but it fails.
Here is the most trivial example (after stripping out use of -vnc and network devices) of recording a few seconds of the windows boot process and then attempting to replay it.

I am running this in a nested VM and panda runs the image fine, booting completely and allowing interaction via vnc. 
My main question, is this a bug in panda or simply lack of support for recording for nested vms? My setup looks like this:
```
Windows 11 Host (HyperV off)
- Ubuntu 22.04.2 LTS Guest
-- Fresh install of Windows 10
```

Record/Replay commands (panda.sh content below)
```
develop@develop-virtual-machine:~$ ./panda.sh /home/develop/windows_hdd.img --monitor stdio -m 4096
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) VNC server running on 127.0.0.1:5900

(qemu) begin_record test4.rec
(qemu) writing snapshot:	./test4.rec-rr-snp
opening nondet log for write:	./test4.rec-rr-nondet.log

(qemu) end_record
(qemu) Time taken was: 10 seconds.
Checksum of guest memory: 0xd6bbcf29
Finalizing the recording
...complete!
Recording ready for use.

(qemu) quit
develop@develop-virtual-machine:~$ ./panda.sh -replay test4.rec --monitor stdio -m 4096
QEMU 2.9.1 monitor - type 'help' for more information
(qemu) loading snapshot
... done.
opening nondet log for read :	./test4.rec-rr-nondet.log
RR rr_assertion `current_item' failed at /panda/panda/src/rr/rr_log.c:1004
Current log point:
{guest_instr_count=2286947}
Next log entry type: RR_INPUT_4
Current replay point:
{guest_instr_count=2286447}

```

panda.sh contents:
```
docker run --workdir /home/develop --privileged --net=host -it --rm -v /home/develop:/home/develop pandare/panda panda-system-x86_64 $@
```

The docker image is the latest on dockerhub:
```
pandare/panda   latest    87fe24dd9348   6 days ago     14.5GB
```
And the version output:
```
./panda.sh --version
QEMU emulator version 2.9.1 (-dirty)
Build date Aug 17 2023
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
```

The recording is 134MB, higher than githubs 25 MB limit, any preferred storage location?

**Comment by AndrewFasano** [comment]
I don't think the issue is the nested VM setup, I suspect record and replay is hitting some edge cases in windows 10 boot. Boot is generally a stress test of record and replay since lots of hardware interactions happen that the RR system has to get perfectly right. Most of our work on and testing of PANDA's RR system was done long before Windows 10 was out (IIRC we tested booting windows XP and maybe windows 7 in addition to a few linux distros and got those working).

Even for non-RR uses, getting Windows 10 to work well under panda can be a bit of a pain - you can find some discussion in our slack, but it seems like you can do it if you disable lots of unnecessary services and OS options, but it's (unfortunately) not something that just works. When we eventually upgrade to a newer version of QEMU this should be a lot easier.

Depend on your goals (and if you already got Windows 10 working well under normal panda use), I'd recommend either:
* Try to start your recording after boot with your Windows 10 guest
* Try an older version of Windows

**Comment by Phasip** [comment]
Thank you, this saves me the trouble of setting up a dedicated panda system!
 
Panda without replay works fine for my windows 10 guest (very slow, but this is expected)
The original issue was for a booted system - but what I want to do involves both networking and usb so maybe that was the culprit at that point.

I'll close this as there is already a task for newer QEMU.
