### ISSUE TITLE
timer.h causing build failure

### ISSUE THREAD

**Issue by DEichEich** [panda-re/panda#158]
I was trying to interact with the QEMU clock when I came across a few errors in `include/qemu/timer.h`. I think these errors are due to changes in C and GCC.

On line [529](https://github.com/panda-re/panda/blob/8905f3567d705bbfac536906640afa7767fec755/include/qemu/timer.h#L529):
Is: `QEMUTimer *ts = g_malloc0(sizeof(QEMUTimer));`
Should be: `QEMUTimer *ts = (QEMUTimer*)g_malloc0(sizeof(QEMUTimer));`

On line [967](https://github.com/panda-re/panda/blob/8905f3567d705bbfac536906640afa7767fec755/include/qemu/timer.h#L967):
Is :             `                              "rdhwr  %0, "rd"\n\t"   \`
Should be: `                              "rdhwr  %0, " rd "\n\t"   \` (Missing spaces around `rd`)

**Comment by moyix** [comment]
Yes, there are quite a few of these unfortunately – I think they are actually due to the fact that we're including C headers in C++ code (e.g., here the need to cast a `void *` to the correct type explicitly is a C++ requirement). So far we've been patching them with #define hacks or modifying the QEMU source if that doesn't work.

I think we'd be okay with accepting a patch, but we're trying to keep these to a minimum, since they make it harder to stay synchronized with the QEMU master.
