### ISSUE TITLE
osi_linux d_entry error

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#181]
Hi!

I'm trying to taint a file using the taint2 and file_taint plugins. I have created a recording by the name of linux_hd_test2 and I try to play it back using:

`./qemu-system-x86_64 -L /usr/share/qemu -replay linux_hd_test2 \`
`-monitor stdio -pandalog linux_hd_test2.plog \`
`-os linux-32-debian-3.16.0-4-586 \`
`-panda osi \`
`-panda syscalls2:profile=linux_x86 \`
`-panda osi_linux:kconf_group=debian-3.16.0-4-586:32 \`
`-panda taint2 \`
`-panda file_taint:filename=apple.txt,pos=0,first_instr=1 \`
`-panda tainted_instr`

It seems to work at first, but then I get littered with d_entry errors:

`QEMU 2.8.50 monitor - type 'help' for more information`
`(qemu) loading snapshot`
`... done.`
`opening nondet log for read : ./linux_hd_test2-rr-nondet.log`
`./linux_hd_test2-rr-nondet.log: 241731358 instrs total.`
`linux_hd_test2: 2428030 ( 1.00%) instrs. 1.83 sec. 0.24 GB ram.`
`linux_hd_test2: 5001717 ( 2.07%) instrs. 2.59 sec. 0.26 GB ram.`
`[..]`
`saw open of file we want to taint: [apple.txt] insn 48779406`
`taint2: __taint_enable_taint`
`taint2: Allocating large fast_shad (2147483648 bytes).`
`taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7ff761fca010.`
`taint2: Allocating small fast_shad (256 bytes) using malloc @ 7ff75b19c120.`
`taint2: Allocating small fast_shad (2048 bytes) using malloc @ 7ff75a5846d0.`
`taint2: Allocating small fast_shad (685568 bytes) using malloc @ 7ff764958010.`
`taint2: Linking taint ops from ./panda/plugins/panda_taint2_ops.bc`
`taint2: Done initializing taint transformation.`
`taint2: Done processing helper functions for taint.`
`taint2: Done verifying module. Running...`
`linux_hd_test2: 50816915 ( 21.02%) instrs. 20.60 sec. 0.57 GB ram.`
`linux_hd_test2: 53353101 ( 22.07%) instrs. 31.97 sec. 0.77 GB ram.`
`[...]`
`INFO(/home/anatoly/Downloads/panda2-git2/panda/panda/plugins/osi_linux/osi_linux.h:read_dentry_name): Error reading d_entry.`
`INFO(/home/anatoly/Downloads/panda2-git2/panda/panda/plugins/osi_linux/osi_linux.h:read_dentry_name): Error reading d_entry.`
`INFO(/home/anatoly/Downloads/panda2-git2/panda/panda/plugins/osi_linux/osi_linux.h:read_dentry_name): Error reading d_entry.`
`linux_hd_test2: 70236760 ( 29.06%) instrs. 77.17 sec. 1.09 GB ram.`
`INFO(/home/anatoly/Downloads/panda2-git2/panda/panda/plugins/osi_linux/osi_linux.h:read_dentry_name): Error reading d_entry.`
`[...]`

I'm not sure what would cause this error. Is this a bug in the osi_linux plugin or might it be an indication that the configuration file for the system is incorrect? Thanks for any help in advance.

**Comment by m000** [comment]
It's been a while since I last worked with the code, but IIRC this
shouldn't be a real problem (that's why it is only INFO). File names are
resolved from file descriptors. But file descriptors may also represent
other types of resources, in which case, read_dentry_name is expected to
fail.

Can you check if this is the case for your recording?
E.g. if you can see some file names reconstructed, then the messages should
be safe to ignore.

M.

2017-06-21 21:29 GMT+03:00 Anatoly Tverdovsky <notifications@github.com>:

**Comment by antverdovsky** [comment]
@m000 Thanks for the response! When I replay the recording, I see `saw open of file we want to taint: [apple.txt] insn 48779406` so I am pretty sure it is able to reconstruct the file name, but I don't see any other commands happening like `read` or `close` which is why I am concerned that those commands are happening but are not visible due to the `d_entry` error. Shouldn't I see other taint logs beside just `open`?

**Comment by moyix** [comment]
Is it possible that the program you're tracing doesn't use read() but rather mmap() or something like that? If you run the same program under strace, do you see it calling read() on that file descriptor?

**Comment by m000** [comment]
Looking closely, I saw you're running linux-32-debian-3.16.0-4-586.

Were you able to compile and run the kernel_info module so that you extract
the appropriate offsets for the kernel?

IIRC, around that kernel version some internal data structures changed. So
traversing them to get the path components no longer worked.
I didn't update the fd resolution code to work with the new kernel at that
time because I didn't really need it, and it was becoming apparent that
this was a moving target.

If you want the VM I had used (runs debian-3.2.81-686-pae), I still have it
on my desktop. But this should take at least a few days to retrieve
(currently out of office).

Making the fd resolution code more generic would be nice. But this should
need quite some effort. Currently, the code is generic with regard to the
member offsets of the data structures that need to be traversed. This has
to be extended and also make the code generic with regard to the data
structures themselves. I.e. the osi_linux module should also read a
description of how to traverse the kernel data structures, depending on the
kernel version.

Otherwise we would need adding new traversal code each time something
breaks. Which would seemingly become hairy fairly quickly.

M.



2017-06-21 22:02 GMT+03:00 Anatoly Tverdovsky <notifications@github.com>:

**Comment by antverdovsky** [comment]
@moyix Yes, the program mostly uses just `read`, `write`, `close`, `open`. I tried it with `strace` and it contains those functions. Also, I tried making another replay based off of the [taint2 HDD test](https://raw.githubusercontent.com/panda-re/panda/master/panda/plugins/taint2/tests/full_system/hard_drive/linux_hd_test.c) and I got the same errors, albeit a lot less of them.

@m000 I did generate a configuration file for the Debian guest and I added the configuration to PANDA. I was able to generate it successfully with the exception of the `mnt_parent_offset` and `mnt_mountpoint_offset` fields because the Linux kernel has changed and no longer has these properties, as you said (I also saw this in issue #97). I had to guess for these so for these two fields I picked the same values that came with all of the other configurations. If I had to guess, I would think the issue would most likely be here. If it's not too much of a hassle, I would certainly appreciate your Debian 3.2.81 VM, since I'm not sure how I can make mine compatible with PANDA.

**Comment by moyix** [comment]
As a warning, the taint2 HDD test is unlikely to work at the moment – it's designed to test a portion of the taint2 system we haven't yet ported over (hard drive taint). It's pretty much guaranteed not to transfer taint under the current system, because we don't model the hard drive. So I think this explains why you aren't seeing any taint.

We expected this to be a problem, but in practice modern OSes perform so much caching that as long as you taint file data when it's read into memory that will usually capture everything you want. If you have a use case that specifically requires taint to go from memory, into the hard drive and back out, please let us know so we can bump that feature's priority a bit on the TODO list...

**Comment by m000** [comment]
I've repackaged the VM and sent you an email with the url. I'm not posting the url publicly for the moment, but I'm willing to share with anyone interested.

**Comment by antverdovsky** [comment]
I tried it today with PANDA1 and it seems to have fixed the issue though I was getting some strange "EAX hypercall" errors with PANDA2. I think for now I might just keep using PANDA1 since that seems to be more compatible with the type of tainting I need to do. Thanks again for your help guys!

**Comment by julioauto** [comment]
I wish this issue had been more thoroughly investigated, as I'm facing the same problem now. Downgrading to PANDA1 hardly seems like a proper fix.

My VM is fairly recent, an Ubuntu 16.04.3. I used the kernelinfo module to capture the required offsets and putting them in the config. Other than that, what I'm seeing is pretty much the same as the original reporter. I record my execution, I reply with file_taint to get the offset of the first tainting instruction (using 'notaint') and then use that to actually run tainted_instr. All the while I'm flooded with the d_entry errors (which I'm ignoring as per the information in this page) and a few "probably not a Panda Hypercall" instances. 20 minutes later I'm left with pandalog that spits out exactly one instruction ('pc' and 'instr' fields) that seems **way too high** to be correct: 18446744073709551615, for both values (my execution record has 504064667 instructions, per the output).

My use case is trying to analyze [this](http://bugzilla.maptools.org/show_bug.cgi?id=2750). The buggy tool opens the PoC file, reads 8 bytes from it, and then mmap's it, reading the data from the mmap'ed buffer. So I'm assuming I should at least see instructions concerning the read part?

Also, would mmap NOT be tainted? (wondering why @moyix asked if "the program you're tracing doesn't use read() but rather mmap() or something")

**Comment by moyix** [comment]
Since libtiff is very self-contained, the simplest thing for you to do is just build a 32-bit version of the PoC and then run it on a supported guest VM using the `run_debian.py` script, which will take care of getting the binary and its input into the VM, starting the program, recording everything, etc. It will automatically download a VM image (...from a server that I've just realized has gone down while I'm out of town – sorry. It will be back up January 4th, but in the meantime you can download the image here instead: http://giantpanda.gtisc.gatech.edu/~brendan/wheezy_panda2.qcow2) that uses a kernel with the `linux-32-lava32` profile. Unless you have a specific reason to go bug-hunting to figure out why it's not working with your specific guest kernel, this is the best option.

In the example you mentioned, you should see `file_taint` taint the 8 bytes from the `read` call, yes. It looks something like:

```*** applying uniform taint labels 1..8 to buffer @ 10456388                   
8 bytes labeled for this read```

The file_taint plugin currently only supports `read`. Supporting `mmap` is harder since you can't just intercept a system call, you have to watch every memory read and check if it comes from a memory-mapped file you want to taint. It's doable but hasn't been done.

**Comment by julioauto** [comment]
Thanks, @moyix . I did notice run_debian.py (actually via taint_debian.py) yesterday but haven't tried it yet.

To be honest, the libtiff thing isn't of much use to me besides being a test case for PANDA. What I'm really trying to understand is how suitable PANDA is to do this kind of analysis repetitively and with multiple targets, various environments, etc. So getting a sense of these limitations (specific supported kernels, untainted syscalls) is actually key for me.

**Comment by julioauto** [comment]
OK, I see what's going on here...

In a nutshell, PANDA was never seeing the read() calls return, so it obviously couldn't taint the bytes read. Why it couldn't see the returns really puzzled me, though, especially because *some* reads (on other files) were being observed (as per debug logs).

Turns out the way PANDA watches syscall returns is by keeping a map of _return points_: every time a syscall is being entered into, the expected/calculated return point is added to the map; later, if a block being translated from the same process starts with that address, then it must be that syscall returning.

The above is not bad, but there's an issue in how the return address is computed. As one can see on [this file](https://github.com/panda-re/panda/blob/cf5b6f73916a5ea13f02fa74dd1c3cab6b830ef7/panda/plugins/syscalls2/syscalls2.cpp#L93), we have this block of code:
```
    // Check if the instruction is syscall (0F 05) or  sysenter (0F 34)
    if ((buf[0]== 0x0F && buf[1] == 0x05) || (buf[0]== 0x0F && buf[1] == 0x34)) {
        return pc+11;
    }
    // Check if the instruction is int 0x80 (CD 80)
    else if (buf[0]== 0xCD && buf[1] == 0x80) {
        return pc+2;
    }
```
You see, if the system call is invoked via syscall/sysenter, the computed return address is EIP + 11 (I suppose this offset was good for some kernel?). However, the code on the vDSO running on my kernel, looks like this:
```
0xb7758c2d:  sysenter 
0xb7758c2f:  int    0x80
0xb7758c31:  pop    ebp
0xb7758c32:  pop    edx
0xb7758c33:  pop    ecx
0xb7758c34:  ret    
0xb7758c35:  lret   0xfffa
0xb7758c38:  jmp    DWORD PTR [ebx]
```
So PANDA expects the system calls to return at that `jmp` instruction (because that's where the address of sysenter + 11 adds up to), but the kernel actually returns at the `pop ebp` instead. (The reason why the kernel resumes execution there is a little beyond the scope of this comment, but suffices to say it's the saved IP determined [here](http://elixir.free-electrons.com/linux/v4.4.108/source/arch/x86/entry/common.c#L424) to be the location of the 'int80_landing_pad', which in turn is defined [here](http://elixir.free-electrons.com/linux/v4.4.108/source/arch/x86/entry/vdso/vdso32/system_call.S#L69))

All of the above means that PANDA needs a better way to calculate where system calls will return, and such way may need to be kernel-version-aware. In the meantime I just changed that offset from 11 to 4 and I can see that PANDA now taints the 8 bytes read. 

By the way, the reason why some reads were returning fine was that they were invoked via `int 0x80`, for which the current of calculating return address (PC+2) works fine. All of these reads were for .so files, so I'm guessing either the ELF loader and/or the code for dlopen() doesn't use the vDSO and relies on some other way instead.

**Comment by moyix** [comment]
Good catch. This does seem like a hard problem to solve generically; the kernel is free to return from a system call wherever it pleases, but we still need some way to match up returns with their calls.

I also now wonder if the current implementation is broken when there are multiple threads making system calls in the application – if we're just looking at the return address, is it possible we could have mismatch between the call and the return?
