### ISSUE TITLE
on_new_process event in Linux gives wrong process name

### ISSUE THREAD

**Issue by wbierman** [panda-re/panda#186]
When `on_new_process` callbacks are called in the OSI plugin, for applications which are run from `bash`, the actual application is not yet loaded.  `bash` begins new processes by `fork()`ing itself and then calling `execve()` thereby replacing the bash PID created by `fork()` with the target binary.

Example output with `-DPROC_EVENTS_DBG` added to compile flags:

Note that the `on_new_process` line is triggered by a registered callback in a plugin.

```
*+**********
*       bash            1987    1985    f7227000
*       init            1       0       f637e000
*       udevd           296     1       f7141000
*       udevd           737     296     f7094000
*       udevd           738     296     f71df000
*       rpcbind         1752    1       f70db000
*       rpc.statd       1789    1       f703f000
*       dhclient        1803    1       f72f9000
*       rpc.idmapd      1825    1       f7107000
*       init            1984    1       f7224000
*       bash            1985    1984    f725b000
*+**********
on_new_process: bash
w:      847596 ( 14.14%) instrs.    0.39 sec.  0.13 GB ram.
*+**********
*       w               1987    1985    f7227000
*       init            1       0       f637e000
*       udevd           296     1       f7141000
*       udevd           737     296     f7094000
*       udevd           738     296     f71df000
*       rpcbind         1752    1       f70db000
*       rpc.statd       1789    1       f703f000
*       dhclient        1803    1       f72f9000
*       rpc.idmapd      1825    1       f7107000
*       init            1984    1       f7224000
*       bash            1985    1984    f725b000
*+**********
```

Notice that the newly created process with ID `1987` has the name `bash` but is then replaced by `w`.  This was caused by me executing `w` via the `bash` prompt in the guest.

@m000 I am tagging you in this per the recommendation of @moyix.

**Comment by m000** [comment]
This is a known issue. I've worked around it by deferring process name
resolution. You can check the prov_tracer plugin in my  prov2r branch for a
code sample. IIRC I use a boolean flag. When a process where the flag  is
not set executes, I repeat the name resolution. That worked good enough for
me.

If you have some spare cycles, you may try to automate this. E.g. before
the user callback is invoked, you can disable all plugins , proceed replay
until you can get the real process name, and then rewind and restore
plugins.

Not sure if this is really feasible though. Maybe Brendan can weigh in. I'm
AFK this week so I'm answering with what I can recall. I should be able to
provide more details next week.

M.

On Jun 26, 2017 8:36 PM, "Bill Bierman" <notifications@github.com> wrote:

When on_new_process callbacks are called in the OSI plugin, for
applications which are run from bash, the actual application is not yet
loaded. bash begins new processes by fork()ing itself and then calling
execve() thereby replacing the bash PID created by fork() with the target
binary.

Example output with -DPROC_EVENTS_DBG added to compile flags:

Note that the on_new_process line is triggered by a registered callback in
a plugin.

*+**********
*       bash            1987    1985    f7227000
*       init            1       0       f637e000
*       udevd           296     1       f7141000
*       udevd           737     296     f7094000
*       udevd           738     296     f71df000
*       rpcbind         1752    1       f70db000
*       rpc.statd       1789    1       f703f000
*       dhclient        1803    1       f72f9000
*       rpc.idmapd      1825    1       f7107000
*       init            1984    1       f7224000
*       bash            1985    1984    f725b000
*+**********
on_new_process: bash
w:      847596 ( 14.14%) instrs.    0.39 sec.  0.13 GB ram.
*+**********
*       w               1987    1985    f7227000
*       init            1       0       f637e000
*       udevd           296     1       f7141000
*       udevd           737     296     f7094000
*       udevd           738     296     f71df000
*       rpcbind         1752    1       f70db000
*       rpc.statd       1789    1       f703f000
*       dhclient        1803    1       f72f9000
*       rpc.idmapd      1825    1       f7107000
*       init            1984    1       f7224000
*       bash            1985    1984    f725b000
*+**********

Notice that the newly created process with ID 1987 has the name bash but is
then replaced by w. This was caused by me executing w via the bash prompt
in the guest.

@m000 <https://github.com/m000> I am tagging you in this per the
recommendation of @moyix <https://github.com/moyix>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/panda-re/panda/issues/186>, or mute the thread

**Comment by wbierman** [comment]
I have been experimenting with monitoring calls to `clone()`, `fork()`, `execve()`, `_exit()`, and `exit_group()`, and the initial results are encouraging.

**Comment by wbierman** [comment]
I'm going to withdraw this report as it is actually working the way it should, since the process actually is a `bash` process when it is first created.  Delayed resolution is one solution, but a more sound one would be to monitor for `execve()` from the new process, and re-trigger the on-new-process event when it is executed.

**Comment by m000** [comment]
@wbierman That's not a bad idea, but it should probably be pushed to osi_linux as `execve`is OS-specific.
