### ISSUE TITLE
Poor Guest Performance With QEMU

### ISSUE THREAD

**Issue by antverdovsky** [panda-re/panda#198]
Hi everybody,

I've been using PANDA over the past few weeks and it is a great project which works well with a non-resource hungry CLI Debian image I have. I would like to now use PANDA with a slightly more complex GUI Linux OS in order to capture some modern Firefox tests. Unfortunately, I am getting very poor performance when running the OS with PANDA and QEMU. I've tried allocating more RAM but that did not help much, and also using `-smp` to add more CPUs causes a segmentation fault. I know PANDA doesn't support hardware virtualization and therefore it won't work with KVM, but is it possible to use with KQEMU since KQEMU doesn't use hardware virtualization?

**Comment by moyix** [comment]
Our record/replay system depends on being able to instrument individual instructions and do precise counting of the number of instructions executed so far. These features require QEMU to run in its software emulation (TCG) mode. So unfortunately kqemu won't work either. And although it's not great that `-smp` is causing a segfault (we should fix that), it doesn't actually make QEMU any faster, because QEMU uses a lock to make sure that only one CPU runs at a time.

Usually what we do is get the VM set up under KVM – install software, prepare the environment, etc. Then reboot into TCG mode and create the recording for the experiment you're interested in.

Issue #177 will make this process a bit more seamless, by allowing you to transition between KVM and TCG mode without rebooting.

**Comment by antverdovsky** [comment]
Thank you @moyix. Do you have any tips that can be used to speed up the execution? I've set up my Linux image in KVM and installed all of the necessary software I'd like to test with PANDA but as soon as I boot into TCG mode, the OS is barely usable. I'm trying to run some tests which require Firefox, but it takes roughly a minute just to open Firefox and load google. I feel like I'm doing something wrong because the host machine I'm working on has 16 cores and 128GB of RAM.

**Comment by m000** [comment]
@antverdovsky You're not doing anything wrong, it is slow.

@moyix After the resolution of #177, will you be able to switch back and forth between KVM and TCG? Or will it be a one-time switch to TCG?

**Comment by m000** [comment]
@moyix Any clue if the TCG TB cache handling has improved in the past decade? The 2005 QEMU paper mentions that: "A 16 MByte cache holds the most recently used TBs. For simplicity, it is completely flushed when it is full."
If this is still true, it sounds horrible for running programs like Firefox. Maybe throwing your spare GB on the TB cache could speed up things?

**Comment by antverdovsky** [comment]
@m000, I'm sorry I'm not really sure what you mean by TB. How can I add more to it?

**Comment by moyix** [comment]
@m000 You would be able to switch back and forth (though if you do that during recording the replay won't work, of course). It works by making the VM states between KVM and TCG compatible so you can do live migration between them.

As for the TB cache, I believe the `-tb-size` option controls this. By default it's set to 1/4 of guest RAM.

**Comment by antverdovsky** [comment]
@moyix, I tried it with `-tb-size` but sadly the performance is still unchanged :(. I guess I will find a more lightweight OS to conduct my Firefox experiments on.

**Comment by phulin** [comment]
I'm going to close this. Unfortunately, we're limited to QEMU's built-in performance. We could work on it but it's not a high priority since there's not so much we can do.
