### ISSUE TITLE
Possible to trigger begin_record / end_record from the vm?

### ISSUE THREAD

**Issue by piec** [panda-re/panda#249]
Hi,

I was wondering if it was already possible to trigger begin_record / end_record from the vm itself
It would be handy when you just want to record precisely the execution of a command in a shell like this:

```shell
/bin/trigger begin_record
./program
/bin/trigger end_record
```

If not already implemented I guess panda would need a new hypercall? + a linux module to expose it to userspace right?

---

Or there's maybe another way to achieve this?

Cheers,
Pierre

**Comment by moyix** [comment]
The hypercalls PANDA uses are triggered by executing CPUID with magic values in the registers, so they are designed to be triggered from userspace without any kernel changes. Otherwise, you're on the right track!

Note that if you're running programs on Linux, it may be simpler to just use the `run_debian.py` script, which can be found in the `panda/scripts` directory.

**Comment by piec** [comment]
Cool I'll try to implement a new hypercall for fun but yes `run_debian.py` is really fit for what I'm doing
Thanks :)
