### ISSUE TITLE
get_mod_base assertion failed in wintrospection

### ISSUE THREAD

**Issue by Kyomian** [panda-re/panda#302]
When running:
`./qemu-system-i386 -replay <replay> -m 2048 -os windows-32-7 -panda 'osi;osi_test'`

I got this error `get_mod_base: Assertion !panda_virtual_memory_rw(cpu, mod+LDR_BASE_OFF, (uint8_t *)&base, sizeof(PTR), false)' failed.
Aborted (core dumped)`

Am I missing something? I suspect it has to do with pages.

**Comment by moyix** [comment]
Yep, it looks like it was trying to access some memory that was paged out. We should probably not be asserting there, but rather dealing with that gracefully and returning NULL or similar.

**Comment by Kyomian** [comment]
@moyix This error occurred at `get_libraries(env, process)` - the function that returns userspace libraries in the specified process. And the callback is at `after_block_exec`. I suspect that the memory that contains the libraries are being paged out? after block executes... Is there a way to rectify this?

**Comment by Kyomian** [comment]
Ok I narrowed it down to `get_next_mod(cpu,  current_mod)`, which is the problematic function. `panda_virtual_memory_rw` in `get_next_mod` is not successful, even though the `panda_virtual_memory_rw` when reading EPROCESS and PEB are successful..

**Comment by moyix** [comment]
The libraries themselves may not be paged out; `get_libraries` traverses the metadata that is kept describing where each library is loaded (on Windows, this is the `LDR_DATA_TABLE_ENTRY` linked list, which is accessible from the `PEB`).

It's likely to be a paging problem – `panda_virtual_memory_rw` tries to map the virtual address to a physical one and then retrieve the content of that page. So if it's paged out, the virtual address will be unmapped, and it will return -1.

Since this is happening in `get_next_mod`, then it's possible it managed to read part of the module list. So we could either return the partial list, or throw away the libraries collected so far and return NULL. I'm more inclined to the latter, since we don't have any way to signal to the caller that the list is incomplete.

**Comment by Kyomian** [comment]
> then it's possible it managed to read part of the module list

No, it couldn't read any parts of the module list. `get_next_mod` reads in the first module too, and that failed.

This means that `get_libraries` simply do not work at all. I couldn't get the usermode libraries at all.

**Comment by Kyomian** [comment]
Ok, I solved it using `asid_changed`... `asid_changed` must be used though.
