### ISSUE TITLE
cpu_restore_state not triggering for faults caused by calls

### ISSUE THREAD

**Issue by leowweixiang** [panda-re/panda#335]
I noticed cpu_restore_state does not trigger for some cases like "call 0x60000000" that cause a page fault. Can't give a precise example at the moment. Where should I be looking at to fix this?

**Comment by moyix** [comment]
Hmm, I think you might want to look in `target/i386/translate.c`. Page faults that occur during execution would call `cpu_restore_state`, but since that fault will be triggered at translation time (when it tries to fetch the instruction bytes at `0x60000000`) it probably won't go through the `cpu_restore_state` path.

**Comment by moyix** [comment]
Any luck tracking this down @leowweixiang ?
