### ISSUE TITLE
Compilation terminated

### ISSUE THREAD

**Issue by yikuoyansui** [panda-re/panda#385]
/home/parallels/panda/panda/scripts/panda/panda/plugins/tainted_net/tainted_net.cpp:22:31: fatal error: taint2/taint2_ext.h: No such file or directory
compilation terminated.
/home/parallels/panda/panda/scripts/panda/rules.mak:97: recipe for target 'panda/plugins/tainted_net/tainted_net.o' failed
make[2]: *** [panda/plugins/tainted_net/tainted_net.o] Error 1
/home/parallels/panda/panda/scripts/panda/panda/Makefile.panda.target:42: recipe for target 'plugin-tainted_net' failed
make[1]: *** [plugin-tainted_net] Error 2
Makefile:324: recipe for target 'subdir-i386-softmmu' failed
make: *** [subdir-i386-softmmu] Error 2

**Comment by moyix** [comment]
I think this is caused by not having LLVM 3.3 installed. When this happens PANDA will try to go ahead with the build but exclude taint-related plugins, but it looks like a couple plugins that depend on taint have been included in the main plugin list by accident. I'll move them over, which should fix this particular issue, but if you do want to use the taint system you'll still have to install (or build) LLVM 3.3.
