### ISSUE TITLE
Can I use plugin to skip a function?

### ISSUE THREAD

**Issue by LittleSec** [panda-re/panda#417]
I want to write a plugin to hook a function in simulated binary(for example, use a func wrote in plugin to replace the target func). I obtained the entry address of the target function by reverse engineering. And I also know what the return state of the target function.
1st idea: use `on_ret` mechanism to update the return state I want, but I don't want panda run the target function(because the target function may have some problems).
2rd idea: use `insn_translate()` and `insn_exec callback()` to modify the pc to the function return address when the pc is the entry address of the target function.
I want to sure If I can modify the pc? or has any ideas to implement a plugin similar to a hook?
thank you.

**Comment by moyix** [comment]
Yes, I've done this before. The way to do it is in a before_block_exec_invalidate_opt – when you see you're about to enter the target function you can change the PC to whatever you want, write things to memory, set registers, etc.

Note that this probably *won't* work in replay since everything needs to be exactly synchronized to the recording there.

**Comment by LittleSec** [comment]
you mean that we can use `envp->regs[15] = new_pc // ARM` to change pc?
I also want to know if the static bool value `in_call` in call_function() means in myfunc call?

**Comment by moyix** [comment]
Yes, that's what that plugin does. But it should still be good as an example of how to modify the execution state of the machine at runtime.

Retranslation is still needed because you're going to be executing different code than what it expected as a result of the plugin. Even if you're just skipping code, it will still need to translate the code you're replacing it with.

**Comment by LittleSec** [comment]
There are 2 callback functions will  be called before execution of every basic block,  `before_block_exec_invalidate_opt()` and `before_block_exec()`. Do you know which one will be executed firstly? or it is uncertain?

**Comment by moyix** [comment]
`before_block_exec_invalidate_opt` will be called first. It's invoked here:

https://github.com/panda-re/panda/blob/master/cpu-exec.c#L816

whereas `before_block_exec` is invoked a little later, here:

https://github.com/panda-re/panda/blob/master/cpu-exec.c#L188
