### ISSUE TITLE
pypanda - protobuf fatal error

### ISSUE THREAD

**Issue by irwincong** [panda-re/panda#972]
Probably a degenerate case. pyPanda encounters a protobuffer exception with the following code snippet.

```python
#!/usr/bin/env python
from pandare import Panda
panda = Panda(generic='x86_64')
panda = Panda(generic='i386')
```

```
Loading libpanda from /usr/local/lib/python3.8/dist-packages/pandare/data
[libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: plog.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted (core dumped)
```

Reproduced multiple times (with different combinations of generic images) in the latest docker image.

```
$ docker pull pandare/panda
Using default tag: latest
... 8< ...
Digest: sha256:73f0034b0dc4e7b66c8ede9a732166cfc25fb6f97ec07d2202340c3e705b11e6
Status: Downloaded newer image for pandare/panda:latest
docker.io/pandare/panda:latest
```

**Comment by lacraig2** [comment]
We only support one instance of the Panda object running at a time. 

If you'd like to know why: Each Panda object is a full instance of Panda. That means we load a shared object with code for a virtual machine in `libpanda-arch.so` for each object.

Your specific issue arrises because we don't add `RTLD_GLOBAL`. If we do add `RTLD_GLOBAL` we still run into other issues because every global is shared and obviously two panda libraries have basically overlapping global variables.

I'd love to get a solution working with separate namespaces in something like `dlmopen`, but sadly every time I try it out it SEGFAULTs hard in the dynamic linker.

**Comment by irwincong** [comment]
I see. I missed the [dragons section ](https://github.com/panda-re/panda/blob/771aa86b3eb9facb54d05420f22a5c53d8ef2b41/panda/python/docs/USAGE.md#here-be-dragons) in the documentation. Thanks much.

**Comment by irwincong** [comment]
@lacraig2 , I don't have a need right now, but is there a suggested workflow in analyzing the interaction between two systems (e.g., a sensor and a controller)? (Honestly, this is a half-baked idea right now, but I was thinking something like https://github.com/ucsb-seclab/karonte but with Panda).

**Comment by lacraig2** [comment]
That's a neat idea.

If you pursue it I'd recommend you try out python multiprocessing with shared variables. It's really a lot less intimidating than it sound. Python just abstracts away the memory sharing and locks in the background. It makes it seem largely like it's in the same process. We did it for one of my examples in the PyPANDA paper. See here: https://www.github.com/panda-re/bar2021/tree/main/unpacker%2Fpyunpacker.py
