### ISSUE TITLE
PyPanda panda.virt_to_phys gives unexpected result (and taint.py example broken)

### ISSUE THREAD

**Issue by narceritor** [panda-re/panda#978]
Hi,

I'm trying to get `panda/python/examples/taint.py` running. I've done the following adjustments. The if statement would never evaluate to true, `taint_label_ram` was missing an argument and it seemed to me that one has to first translate the VA to a physical address, before tainting RAM.
```
def read(cpu, tb, fd, buf, cnt):
    fname = fd_to_fname(cpu, fd)
    print(f"read {fname}")

    if fname == b"/etc/passwd":
        for idx in range(cnt):
            paddr = panda.virt_to_phys(cpu, buf+idx)
            print(f"Tainting PA {hex(paddr)} (VA {hex(buf+idx)})")
	    panda.taint_label_ram(paddr, idx)
```

Now, the problem is the following:
`PANDA[taint2]: Fatal error- taint query on invalid address 0xffffffffffffffff`
I've provided a log. However, the snippet of interest is probably this:
```
...
Tainting PA 0x2ec15fff (VA 0x555555795fff)
Tainting PA 0xffffffffffffffff (VA 0x555555796000)
...
```
Somehow `panda.virt_to_phys()` translates 0x555555796000 to 0xffffffffffffffff. Another thing that strikes me is that `cnt` has value 32768, whereas `/etc/passwd` only is 1512 bytes.

Maybe I'm missing something.

[taint.log](https://github.com/panda-re/panda/files/6401447/taint.log)

**Comment by lacraig2** [comment]
`0xffffffffffffffff` is `-1` represented as an unsigned integer. That means that the virtual to physical translation could not be done (because it's not mapped).

As for the count I don't have quite enough information to comment other than to say that `sys_read` indicates how many bytes it is _capable_ of reading, not how many bytes are read. If `sys_read` asks for 32768 bytes the system can fill that many, but might not depending on how many bytes are in the file.

You'll find the number of bytes _actually read_ as the return value of sys_read. https://man7.org/linux/man-pages/man2/read.2.html
